# gradient

In [1]:
import torch
A = torch.tensor([
    [1, 10, 100],
    [2, 20, 200],
    [4, 40, 400],
], dtype=torch.float)

In [2]:
B = torch.randn(3, requires_grad=True)

In [3]:
(B @ A).sum().backward()

In [4]:
B.grad

tensor([111., 222., 444.])

In [5]:
B = torch.randn([4, 3], requires_grad=True)

In [6]:
(B @ A).sum().backward()

In [7]:
B.grad

tensor([[111., 222., 444.],
        [111., 222., 444.],
        [111., 222., 444.],
        [111., 222., 444.]])

In [8]:
B = torch.randn([3, 4], requires_grad=True)

In [9]:
(A @ B).sum().backward()

In [10]:
B.grad

tensor([[  7.,   7.,   7.,   7.],
        [ 70.,  70.,  70.,  70.],
        [700., 700., 700., 700.]])